### PR TITLE
Updated core to 1.0.0-beta.14 (fixes number parsing and issue #245)

### PR DESCRIPTION
**Pull request by bianchimro**
This should fix issues with number parsing (with specified separators and parsing options)

### CODE REVIEW

**Comment by mikima** [comment]
tested, it seems that everything is working

**Review by mikima — CHANGES_REQUESTED** [review]
sorry for the duplicate comment.

Decimal separator is working, but not thousands separator, see the screenshoot.
Furthermore, since by default the cell separator is comma AND the default thousand separator is comma it creates unexpected behaviuors.
Below the screenshoot and test dataset.

Screenshot 2021-03-02 at 09 19 04

```
test_us
10.44
76.33
2,923
1,045,442.22
1,23
```

**Comment by bianchimro** [comment]
hi @mikima i updated the pull request
in the dataset you tested:

```
test_us
10.44
76.33
2,923
1,045,442.22
1,23
```

with thousands separator = "," the last number should not be parsed (we need 3 digits after thousands separator)

**Comment by mikima** [comment]
@bianchimro yes the last one was intentionally an error to check how errors are handled. i'll test asap

**Pull request merged**
